name: project
description: >-
  Entirety of bug tracker
type: object
items:
  project-name:
    type: string
    description: The name of the project.
    required: true
  project-maintainer:
    type: object
    description: The maintainer. Should match the person schema.
    required: false
  project-homepage:
    type: string
    description: A URL for the home page of the project
    required: false
  project-description:
    type: string
    description: A description of the project
    required: false
  project-bugs:
    type: array
    description: >-
      List of bugs, not in any particular order. Should fit the bug schema.
    items:
      type: object
    required: true
